### ISSUE TITLE
Easy Install - Fail

### ISSUE THREAD

**Issue by clockwiseq** [frappe/easy_install#11]
Issue: Easy Install

CentOS 8 new server, ran through the "simple steps" and downloaded the .py file from the githubusercontent.com path and ran the command `python3 install.py --production` and got the following error:

`Logs are saved under /tmp/logs/easy-install__2021-07-01__04-55.log
Error: Unable to find a match: python-setuptools python-devel
Traceback (most recent call last):
  File "install.py", line 495, in <module>
    install_prerequisites()
  File "install.py", line 158, in install_prerequisites
    'sudo yum install -y epel-release redhat-lsb-core git python-setuptools python-devel openssl-devel libffi-devel'
  File "install.py", line 143, in run_os_command
    returncode = subprocess.check_call(command, shell=True, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sudo yum install -y epel-release redhat-lsb-core git python-setuptools python-devel openssl-devel libffi-devel' returned non-zero exit status 1.`

I'm not linux expert, but when I tried to `yum install python-setuptools` it returns an error that the package cannot be found, but `python3-setuptools` is already installed.  So, what do I need to do to get this thing going?

**Comment by AliShaatani** [comment]
same problem.

**Comment by idolaru** [comment]
It failed for me on three instances on AWS, Centos 7, Ubuntu 16.04 and Debian 10.

**Comment by AliShaatani** [comment]
> It failed for me on three instances on AWS, Centos 7, Ubuntu 16.04 and Debian 10.

try on clean ubuntu server 20.04

 with these instructions 
$ sudo apt update
$ sudo apt upgrade
$ export LC_ALL=C.UTF-8
$ sudo apt install python3-testresources
$ wget https://raw.githubusercontent.com/frappe/bench/develop/install.py
$ sudo python3 install.py --production --version 13

**Comment by AliShaatani** [comment]
> Issue: Easy Install
> 
> CentOS 8 new server, ran through the "simple steps" and downloaded the .py file from the githubusercontent.com path and ran the command `python3 install.py --production` and got the following error:
> 
> `Logs are saved under /tmp/logs/easy-install__2021-07-01__04-55.log Error: Unable to find a match: python-setuptools python-devel Traceback (most recent call last): File "install.py", line 495, in <module> install_prerequisites() File "install.py", line 158, in install_prerequisites 'sudo yum install -y epel-release redhat-lsb-core git python-setuptools python-devel openssl-devel libffi-devel' File "install.py", line 143, in run_os_command returncode = subprocess.check_call(command, shell=True, stdout=log_stream, stderr=sys.stderr) File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command 'sudo yum install -y epel-release redhat-lsb-core git python-setuptools python-devel openssl-devel libffi-devel' returned non-zero exit status 1.`
> 
> I'm not linux expert, but when I tried to `yum install python-setuptools` it returns an error that the package cannot be found, but `python3-setuptools` is already installed. So, what do I need to do to get this thing going?

try to test your mariaDB connection by using this command $systemctl status mariadb.service

if the command failed you need to fix your maria server before running the installation again

it happens when you are using MySQL server on the same server

**Comment by idolaru** [comment]
Thank you for your assistance...

Now the installation stopped with this error:

`Passwords saved at ~/passwords.txt
Initializing bench frappe-bench:
	Frappe Branch: version-13
	ERPNext Branch: version-13
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Traceback (most recent call last):
  File "install.py", line 500, in <module>
    install_bench(args)
  File "install.py", line 281, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 416, in run_playbook
    success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.
`

**Comment by AliShaatani** [comment]
> Thank you for your assistance...
> 
> Now the installation stopped with this error:
> 
> `Passwords saved at ~/passwords.txt Initializing bench frappe-bench: Frappe Branch: version-13 ERPNext Branch: version-13 [WARNING]: No inventory was parsed, only implicit localhost is available [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all' Traceback (most recent call last): File "install.py", line 500, in <module> install_bench(args) File "install.py", line 281, in install_bench run_playbook('site.yml', sudo=True, extra_vars=extra_vars) File "install.py", line 416, in run_playbook success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr) File "/usr/lib/python3.8/subprocess.py", line 364, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2. `

Is that a clean server ?

Run this command and type what u will get 

$systemctl status mariadb.service

**Comment by idolaru** [comment]
Clean server, brand new instance on AWS

MariaDB is running, I checked before running the install.

`systemctl status mariadb.service 
● mariadb.service - MariaDB 10.3.31 database server
     Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-10-23 02:29:11 UTC; 3h 31min ago
       Docs: man:mysqld(8)
             https://mariadb.com/kb/en/library/systemd/
   Main PID: 8036 (mysqld)
     Status: "Taking your SQL requests now..."
      Tasks: 30 (limit: 1154)
     Memory: 64.2M
     CGroup: /system.slice/mariadb.service
             └─8036 /usr/sbin/mysqld

Oct 23 02:29:11 ip-172-31-91-13 /etc/mysql/debian-start[8074]: mysql
Oct 23 02:29:11 ip-172-31-91-13 /etc/mysql/debian-start[8074]: performance_schema
Oct 23 02:29:11 ip-172-31-91-13 /etc/mysql/debian-start[8074]: Phase 6/7: Checking and upgrading tables
Oct 23 02:29:11 ip-172-31-91-13 /etc/mysql/debian-start[8074]: Processing databases
Oct 23 02:29:11 ip-172-31-91-13 /etc/mysql/debian-start[8074]: information_schema
Oct 23 02:29:11 ip-172-31-91-13 /etc/mysql/debian-start[8074]: performance_schema
Oct 23 02:29:11 ip-172-31-91-13 /etc/mysql/debian-start[8074]: Phase 7/7: Running 'FLUSH PRIVILEGES'
Oct 23 02:29:11 ip-172-31-91-13 /etc/mysql/debian-start[8074]: OK
Oct 23 02:29:11 ip-172-31-91-13 /etc/mysql/debian-start[8138]: Checking for insecure root accounts.
Oct 23 02:29:11 ip-172-31-91-13 /etc/mysql/debian-start[8142]: Triggering myisam-recover for all MyISAM tables and aria-recover for all Aria tables`

**Comment by idolaru** [comment]
It seems I'm moving forward using the tutorial from here: https://www.digitalocean.com/community/tutorials/how-to-install-an-erpnext-stack-on-ubuntu-20-04

Tutorial and documentation here is not complete.

**Comment by AliShaatani** [comment]
> It seems I'm moving forward using the tutorial from here: https://www.digitalocean.com/community/tutorials/how-to-install-an-erpnext-stack-on-ubuntu-20-04
> 
> Tutorial and documentation here is not complete.

What is the name of that instance ?

**Comment by oscarfuentees** [comment]
> It failed for me on three instances on AWS, Centos 7, Ubuntu 16.04 and Debian 10.

Were you able to install it on Centos7?
