### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'Nonetype' and 'list' 

### ISSUE THREAD

**Issue by El-profesor-0** [frappe/easy_install#23]
I am facing this issue while using 'bench init frappe-bench'.
I have downloaded it using 'pip3 install frappe-bench'
I found this issue closed but no solution has seemed to work.

/usr/local/Cellar/python/3.7.6_1/bin/python3.7: Error while finding module specification for 'frappe.utils.bench_helper' (ModuleNotFoundError: No module named 'frappe')

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('frappe-bench', 'console_scripts', 'bench')()
  File "/Users/narendra/Development/bench-repo/bench/cli.py", line 48, in cli
    if sys.argv[1] in get_frappe_commands() + ["--site", "--verbose", "--force", "--profile"]:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

**Comment by saru2020** [comment]
I have been trying this for quite some time now and still see the same issue. 

**Somehow got bench installed but it did so with some warnings, I thought:**

<img width="574" alt="Screenshot 2020-12-30 at 11 31 16 PM" src="https://user-images.githubusercontent.com/1034916/103372208-65c94980-4af7-11eb-8729-5d0512e0b1e0.png">


**But, after that, when we try to use it, it throws the error. It looks like bench was not properly installed:**

<img width="571" alt="Screenshot 2020-12-30 at 11 31 33 PM" src="https://user-images.githubusercontent.com/1034916/103372224-6feb4800-4af7-11eb-8173-4654bc9671fb.png">


I see so many people have reported the same issue but no proper answer to it.

Is there really a solution to this issue? Could someone from Frappe tech show some light on this, please?

**Comment by gavindsouza** [comment]
This error seems to come up when frappe hasn't been installed properly in your bench's `env`.
